config/routes.rb
Rails.application.routes.draw do

  resources :locations
  root "projects#index"
  resources :materials
  resources :contractors
  resources :uploads
  devise_for :users
  resources :operators
  resources :bid_expenses
  
  resources :petty_cashes do
    resources :particulars
    resources :cash_sources
  end

  resources :equipments do 
    resources :equipment_expenses
  end
  
  resources :projects do 
    resources :billable_materials
    resources :equipment_schedules
    resources :uploads
    resources :material_expenses
    resources :locations
    resources :biddings
    resources :bidders
    resources :bidder_amounts
    resources :bid_collections
  end
    resources :billable_materials
    resources :equipment_schedules
    resources :material_expenses

end

app/models/bidder.rb
class Bidder < ActiveRecord::Base
	belongs_to :bidding
	belongs_to :bid_expense
	belongs_to :project
  has_one :bidder_amount

  def to_s
		name
	end

end

app/controllers/bidders_controller.rb
class BiddersController < ApplicationController
  before_action :set_bidder, only: [:show, :edit, :update, :destroy]

  # GET /bidders
  # GET /bidders.json
  def index
    @bidders = Bidder.all
  end

  # GET /bidders/1
  # GET /bidders/1.json
  def show
  end

  # GET /bidders/new
  def new
    @project = Project.find(params[:project_id])
    @bidder = @project.bidders.build
  end

  # GET /bidders/1/edit
  def edit
    @project = Projct.find(params[:project_id])
  end

  # POST /bidders
  # POST /bidders.json
  def create
    @project = Project.find(params[:project_id])
    @bidder = @project.bidders.create(bidder_params)

    respond_to do |format|
      if @bidder.save
        format.html { redirect_to @project, notice: 'Bidder was successfully created.' }
        format.json { render :show, status: :created, location: @bidder }
      else
        format.html { render :new }
        format.json { render json: @bidder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bidders/1
  # PATCH/PUT /bidders/1.json
  def update
    respond_to do |format|
      if @bidder.update(bidder_params)
        format.html { redirect_to @project, notice: 'Bidder was successfully updated.' }
        format.json { render :show, status: :ok, location: @bidder }
      else
        format.html { render :edit }
        format.json { render json: @bidder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bidders/1
  # DELETE /bidders/1.json
  def destroy
    @project = Projct.find(params[:project_id])
    @bidder.destroy
    respond_to do |format|
      format.html { redirect_to @bidder.project, notice: 'Bidder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bidder
      @bidder = Bidder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bidder_params
      params.require(:bidder).permit(:name)
    end
end

app/helpers/bidders_helper.rb
module BiddersHelper
end

app/views/bidders/_form.html.erb
<%= simple_form_for [@project, @bidder] do |f| %>
  <%= f.error_notification %>
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <% if @bidder.new_record? %>
          <h4>New Bidders</h4>
        <% else %>
          <h4>Update Bidders</h4>
        <% end %>
      </div>
      <div class="panel-body">
      <%= f.input :name, input_html: {class: "input-sm"} %>
  		</div>
			<div class="modal-footer">
        <div class="pull-left">
          <%= link_to "Cancel", project_path(@project), class: "btn btn-warning btn-sm" %>
        </div>
        <div class="pull-right">
          <% if @bidder.new_record? %>
            <%= f.submit "Save", class: "btn btn-primary btn-sm" %>
          <% else %>
            <%= f.submit "Update", class: "btn btn-primary btn-sm" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/bidders/edit.html.erb
<%= render 'form' %>

app/views/bidders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bidders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bidders.each do |bidder| %>
      <tr>
        <td><%= bidder.name %></td>
        <td><%= link_to 'Show', bidder %></td>
        <td><%= link_to 'Edit', edit_bidder_path(bidder) %></td>
        <td><%= link_to 'Destroy', bidder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bidder', new_bidder_path %>

app/views/bidders/new.html.erb
<%= render 'form' %>

app/views/bidders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bidder.name %>
</p>

<%= link_to 'Edit', edit_bidder_path(@bidder) %> |
<%= link_to 'Back', bidders_path %>