config/routes.rb
Rails.application.routes.draw do

  resources :locations
  root "projects#index"
  resources :materials
  resources :contractors
  resources :uploads
  devise_for :users
  resources :operators
  resources :bid_expenses
  
  resources :petty_cashes do
    resources :particulars
    resources :cash_sources
  end

  resources :equipments do 
    resources :equipment_expenses
  end
  
  resources :projects do 
    resources :billable_materials
    resources :equipment_schedules
    resources :uploads
    resources :material_expenses
    resources :locations
    resources :biddings
    resources :bidders
    resources :bidder_amounts
    resources :bid_collections
  end
    resources :billable_materials
    resources :equipment_schedules
    resources :material_expenses

end

app/models/petty_cash.rb
class PettyCash < ActiveRecord::Base
	has_many :particulars, dependent: :destroy
	has_many :cash_sources, dependent: :destroy

	before_save :set_total_cash_on_hand if present?

	def cash_sources_total
		self.cash_sources.sum(:amount) if present?
	end

	def set_total
		self.cash_on_hand + self.cash_sources.sum(:amount)
	end

	def particulars_total
		self.particulars.sum(:amount) if present?
	end

	def set_total_cash_on_hand
		set_total - self.particulars.sum(:amount)
	end
end

app/controllers/petty_cashes_controller.rb
class PettyCashesController < ApplicationController
  before_action :set_petty_cash, only: [:show, :edit, :update, :destroy]

  # GET /petty_cashes
  # GET /petty_cashes.json
  def index
    @petty_cashes = PettyCash.all
  end

  # GET /petty_cashes/1
  # GET /petty_cashes/1.json
  def show
  end

  # GET /petty_cashes/new
  def new
    if PettyCash.last.present?
      @petty_cash_on_hand = PettyCash.last.set_total_cash_on_hand
      @petty_cash = PettyCash.new
    else
      @petty_cash = PettyCash.new
    end
  end

  # GET /petty_cashes/1/edit
  def edit
  end

  # POST /petty_cashes
  # POST /petty_cashes.json
  def create
    @petty_cash = PettyCash.new(petty_cash_params)

    respond_to do |format|
      if @petty_cash.save
        format.html { redirect_to @petty_cash, notice: 'Petty cash was successfully created.' }
        format.json { render :show, status: :created, location: @petty_cash }
      else
        format.html { render :new }
        format.json { render json: @petty_cash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /petty_cashes/1
  # PATCH/PUT /petty_cashes/1.json
  def update
    respond_to do |format|
      if @petty_cash.update(petty_cash_params)
        format.html { redirect_to @petty_cash, notice: 'Petty cash was successfully updated.' }
        format.json { render :show, status: :ok, location: @petty_cash }
      else
        format.html { render :edit }
        format.json { render json: @petty_cash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /petty_cashes/1
  # DELETE /petty_cashes/1.json
  def destroy
    @petty_cash.destroy
    respond_to do |format|
      format.html { redirect_to petty_cashes_url, notice: 'Petty cash was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_petty_cash
      @petty_cash = PettyCash.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def petty_cash_params
      params.require(:petty_cash).permit(:cash_on_hand)
    end
end

app/helpers/petty_cashes_helper.rb
module PettyCashesHelper
end

app/views/petty_cashes/_form.html.erb
<%= simple_form_for(@petty_cash) do |f| %>
  <%= f.error_notification %>
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <% if @petty_cash.new_record? %>
          <h4>New Petty Cash Record</h4>
        <% else %>
          <h4>Update Record</h4>
        <% end %>
      </div>
      <div class="panel-body">
        <% if @petty_cash_on_hand.present? %>
          <%= f.input :cash_on_hand, input_html: {class: "input-sm", value: @petty_cash_on_hand } %>
        <% else %>
          <%= f.input :cash_on_hand, input_html: {class: "input-sm"} %>
        <% end %>
      </div>
      <div class="modal-footer">
        <div class="pull-left">
          <%= link_to "Cancel", petty_cashes_path, class: "btn btn-warning btn-sm" %>
        </div>
        <div class="pull-right">
          <% if @petty_cash.new_record? %>
            <%= f.submit "Save", class: "btn btn-primary btn-sm" %>
          <% else %>
            <%= f.submit "Update", class: "btn btn-primary btn-sm" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/petty_cashes/index.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="box box-solid">
    <div class="box-header with-border">
      <h4 class="pull-left">Petty Cash Records</h4>
      <%= link_to 'New Petty cash', new_petty_cash_path, class: "btn btn-sm btn-primary pull-right" %>
    </div>
    <div class="box-body">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Date</th>
            <th>Cash on Hand</th>
            <th class="tex-muted">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @petty_cashes.order("created_at desc").each do |petty_cash| %>
            <tr>
              <td><%= link_to petty_cash.created_at.strftime("%B %e, %Y"), petty_cash %></td>
              <td><%= number_to_currency petty_cash.set_total %></td>
              <td><%= link_to 'Edit', edit_petty_cash_path(petty_cash) %> | <%= link_to 'Delete', petty_cash, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/petty_cashes/new.html.erb
<%= render 'form' %>

app/views/petty_cashes/show.html.erb
<%provide(:title, "#{@equipment} | equipments") %>
<div class="col-md-10 col-md-offset-1">
  <div class="box box-solid">
  	<div class="box-header with-border">
  		<h5 class="text-center help-block">Petty Cash Record</h5>
    	<h4 class="text-center"><%=@petty_cash.created_at.strftime("%B %e, %Y") %></h4>
    </div>
    <div class="box-body">
      <table class="table">
        <tbody>
          <tr class="bg-gray">
            <td>Cash on Hand</td>
            <td></td>
            <td><%= number_to_currency @petty_cash.cash_on_hand %></td>
            <td><span class="pull-right"><% if @petty_cash.set_total_cash_on_hand.blank? %><%= link_to "Edit", edit_petty_cash_path(@petty_cash) %><% end %></span></td>
          </tr>
      		<tr class="bg-gray">
      			<td colspan="2">Cash Sources:</td>
      			<td colspan="2">
      			<%= link_to 'Add Cash Source', new_petty_cash_cash_source_path(@petty_cash), class: 'btn btn-sm btn-primary pull-right' %></td>
      		</tr>
          <% @petty_cash.cash_sources.each do |cash_source| %>
	          <tr>
	          	<td></td>
	            <td><%= cash_source.description.capitalize %></td>
	            <td><%= number_to_currency cash_source.amount %></td>
	            <td><span class="pull-right"><%= link_to "Edit", edit_petty_cash_cash_source_path(@petty_cash, cash_source.id) %> | <%= link_to 'Delete', petty_cash_cash_source_path(@petty_cash, cash_source.id), method: :delete, data: { confirm: 'Are you sure?' } %></span></td>
	          </tr>
	        <% end %>
	        <tr>
	        	<td></td>
	        	<th>Subtotal</th>
	        	<th><%= number_to_currency @petty_cash.set_total %></th>
	        	<td></td>
	        </tr>
      		<tr class="bg-gray">
      			<td colspan="2">Expenditures:</td>
      			<td colspan="2"><%= link_to 'Add Expenditure', new_petty_cash_particular_path(@petty_cash), class: 'btn btn-sm btn-primary pull-right' %></td>
      		</tr>
	        <tr>
	        	<td class="text-muted">Recipient</td>
	        	<td class="text-muted">Purpose</td>
	        	<td class="text-muted">Amount</td>
	        	<td class="text-muted">Action</td>
	        </tr>
	         <% @petty_cash.particulars.each do |partiulars| %>
	          <tr>
	          	<td><%= partiulars.recipient.capitalize %></td>
	            <td><%= partiulars.description.capitalize %></td>
	            <td><%= number_to_currency partiulars.amount %></td>
	            <td><span class="pull-right"><%= link_to "Edit", edit_petty_cash_particular_path(@petty_cash, partiulars.id) %> | <%= link_to 'Delete', petty_cash_particular_path(@petty_cash, partiulars.id), method: :delete, data: { confirm: 'Are you sure?' } %></span></td>
	          </tr>
	        <% end %>
	        <tr>
	        	<td></td>
	        	<th>Subtotal</th>
	        	<th><%= number_to_currency @petty_cash.particulars_total %></th>
	        	<td></td>
	        </tr>
	        <tr class="bg-gray-active">
	        	<td></td>
	        	<th>Total Cash on Hand</th>
	        	<th><%= number_to_currency @petty_cash.set_total_cash_on_hand %></th>
	        	<td></td>
	        </tr>
        </tbody>
      </table>
	  </div>
	</div>
</div>