config/routes.rb
Rails.application.routes.draw do

  resources :locations
  root "projects#index"
  resources :materials
  resources :contractors
  resources :uploads
  devise_for :users
  resources :operators
  resources :bid_expenses
  
  resources :petty_cashes do
    resources :particulars
    resources :cash_sources
  end

  resources :equipments do 
    resources :equipment_expenses
  end
  
  resources :projects do 
    resources :billable_materials
    resources :equipment_schedules
    resources :uploads
    resources :material_expenses
    resources :locations
    resources :biddings
    resources :bidders
    resources :bidder_amounts
    resources :bid_collections
  end
    resources :billable_materials
    resources :equipment_schedules
    resources :material_expenses

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :contracts
  has_many :uploads
  has_many :contractors, through: :contracts
  has_many :billable_materials, dependent: :destroy
  has_many :materials, through: :billable_materials
  has_many :equipment_schedules, dependent: :destroy
  has_many :equipments, through: :equipment_schedules
  has_many :equipment_expenses
  belongs_to :location
  has_many :project_locations, through: :locations
  has_many :material_expenses
  has_one :bidding
  has_many :bidders
  has_many :bidder_amounts
  has_many :bid_collections
  
  def sub_totals
   self.billable_materials.map { |i| i.total_price }  
  end

  def total_all
   sub_totals.sum
  end

	def total_expenses
	  self.material_expenses.sum(:price) + self.equipment_expenses.sum(:amount) + self.billable_materials.sum(:price) 
	end

  def actual_total_duration
    ((self.start_date.to_i-self.target_date.to_i)/86400).abs
  end
  def date_now
    now = Date.today
  end
  def now_ms
    date_now.to_datetime.to_f
  end
  def actual_start_ms
    self.start_date.to_datetime.to_f
  end
  def actual_end_ms
    self.target_date.to_datetime.to_f
  end
  def one_day
    60 * 60 * 24
  end
  def actual_past_days
    ((now_ms - actual_start_ms)/one_day)
  end
  def actual_rem_days
    (actual_total_duration.to_i - actual_past_days).ceil
  end
  def actual_percentage
    ((actual_past_days*100)/(actual_total_duration.to_i)).ceil
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    if user_signed_in?
      @projects = Project.all
    else
      redirect_to new_user_session_path
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:id_number, :name, :start_date, :target_date, :cost, :location_id, :contractor_ids =>[])
    end
end

app/views/projects/_form.html.erb
<script>
    $(document).ready(function() {
        $("#project_contractor_ids").select2({

        });
    });
</script>

<script>
    $(document).ready(function() {
        $("#project_equipment_ids").select2({

        });
    });
</script>

<%= simple_form_for(@project) do |f| %>

<div class="col-md-8 col-md-offset-2">
  <div class="panel panel-default">
    <div class="panel-heading">
      <% if @project.new_record? %>
        <h4>New Project</h4>
      <% else %>
        <h4>Update Project</h4>
      <% end %>
    </div>
    <div class="panel-body">
      <%= f.input :id_number, label: 'Project ID', input_html: {class: "input-sm"} %>
      <%= f.input :name, label: 'Project Name', input_html: {class: "input-sm"} %>
      <div class="row">
        <div class="col-md-12">
          <label>Location: </i></label>
          <%= f.association :location, label: false, input_html: {class: "input-sm"} %>
          <i><%= link_to 'New Location?', new_location_path, class: 'pull-right' %></i>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <%= f.input :start_date, as: :string, input_html: {class: "datepicker input-sm"} %>
        </div>
        <div class="col-md-6">
          <%= f.input :target_date,  as: :string, input_html: {class: "datepicker input-sm"} %>
        </div>
      </div>
      <%= f.association :contractors, input_html: {class: "input-sm"} %>
      <%= f.input :cost, label: 'Project Cost', input_html: {class: "input-sm"} %>
    </div>
    <div class="modal-footer">
      <%= f.submit class: "btn btn-primary btn-sm pull-right" %>
      <%= link_to 'Cancel', projects_path, class: "btn btn-sm btn-warning pull-left" %>
    </div>
  </div>
</div>
<% end %>

app/views/projects/index.html.erb
<div class="row">
<div class="col-md-10 col-md-offset-1">
<div class="box box-solid">
<div class="box-header with-border">
  <h4 class="pull-left">List of Projects</h4>
  <%= link_to 'New Project', new_project_path, class: "btn btn-sm btn-primary pull-right" %>
</div>
<div class="box-body">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Project Name</th>
      <th>Contractors</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><strong><%=link_to project.name.upcase, project %></strong></td>
        <td>
        <% project.contractors.each do |contractor| %>
          <%=link_to contractor.company, contractor_path(contractor) %><br>
        <% end %>
        </td>
        <td><%= link_to 'Edit', edit_project_path(project) %> | <%= link_to "Delete", project, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="box-footer">

</div>
</div>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.erb
<%provide(:title, "#{@project.name} | projects") %>



<div class="col-md-12">

  <!-- Nav tabs -->
  <div class="card">
    <div class="row">
      <h4 class="text-center help-block"><%=@project.name.upcase %></h4>
    </div><hr>
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a></li>
      <li role="presentation"><a href="#payments" aria-controls="payments" role="tab" data-toggle="tab">Bid Expenses</a></li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Materials <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li role="presentation"><a role="menuitem" data-toggle="tab" tabindex="-1" href="#permits">Materials from Stock</a></li>
          <li role="presentation"><a role="menuitem" data-toggle="tab" tabindex="-1" href="#material_expenses">Materials from Purchase</a></li>
        </ul>
      </li>
      <li role="presentation"><a href="#equipments" aria-controls="equipments" role="tab" data-toggle="tab">Equipments</a></li>
      <li role="presentation"><a href="#reports" aria-controls="reports" role="tab" data-toggle="tab">Reports</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="profile">
        <div class="row">

          <div class="col-md-12">
            <div class="col-md-12">
            <% if @project.start_date <= @project.date_now && @project.target_date >= @project.date_now %>
              <div class="progress-group">
                <% if @project.actual_percentage <= 0 %>
                  <span class="progress-text">Project Progress</span>
                  <span class="progress-number"><%=@project.actual_percentage%>% Completed | 
                    <% if @project.actual_rem_days > 1%>
                      <span><%= @project.actual_rem_days %> Days</span>
                    <% elsif @project.actual_rem_days <= 1 %>
                      <span><%= @project.actual_rem_days %> Day</span>
                    <% end %> Remaining</span>
                  <div class="progress">
                    <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: <%=@project.actual_percentage%>%">
                    </div>
                  </div>
                <% else %>
                  <span class="progress-text">Project Progress</span>
                  <span class="progress-number"><%=@project.actual_percentage%>% Time Elapsed | 
                    <% if @project.actual_rem_days > 1%>
                      <span><%= @project.actual_rem_days %> Days</span>
                    <% elsif @project.actual_rem_days <= 1 %>
                      <span><%= @project.actual_rem_days %> Day</span>
                    <% end %> Remaining</span>
                  <div class="progress active">
                    <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: <%=@project.actual_percentage%>%">
                    </div>
                  </div>
                <% end %>
              </div>
            <% elsif @project.start_date <= @project.date_now && @project.target_date <= @project.date_now %>
              <div class="progress-group">
                <span class="progress-text">Project Progress</span>
                <div class="progress">
                  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                    <span>100% Time Elapsed</span>
                  </div>
                </div>
              </div>
            <% elsif @project.target_date >= @project.date_now && @project.start_date >= @project.date_now %>
              <span class="progress-text">Project Progress</span>
              <div class="progress">
                <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                  <span>0% Time Elapsed</span>
                </div>
              </div>
            <% end %>
            </div>
          </div>
          <div class="col-md-12">
            <table class="table">
              <tbody>
                <tr>
                  <td>Project Name: </td>
                  <td><%= @project.name.upcase %></td>
                </tr>
                <tr>
                  <td>Location: </td>
                  <td><%=@project.location %></td>
                </tr>
                <tr>
                  <td>Duration: </td>
                  <td><%=@project.actual_total_duration%> CD</td>
                </tr>
                <tr>
                  <td>Starting Date: </td>
                  <td><%=@project.start_date.strftime("%B %e, %Y") %></td>
                </tr>
                <tr>
                  <td>Target Date: </td>
                  <td><%=@project.target_date.strftime("%B %e, %Y") %></td>
                </tr>
                <tr>
                  <td>Project Cost: </td>
                  <td><%= number_to_currency @project.cost %></td>
                </tr>
                <tr>
                  <td><% if @project.contractors.count > 1 %>Contractors: <% else %> Contractor: <% end %></td>
                  <td>
                    <% @project.contractors.each do |contractor| %>
                      <u><%= link_to contractor, contractor_path(contractor) %></u><% if @project.contractors.count >= 2 %>, <% end %>
                    <% end %>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          <div class="modal-footer">
            <%=link_to "Update Info", edit_project_path(@project), class: "btn btn-primary btn-sm" %>
          </div>
        </div>
        <div class="row"><hr>
          <h4>Expenses</h4>
          <div class="col-md-12">
            <table class="table">
              <tbody>
                <tr>
                  <td>Billable Materials</td>
                  <td><%=number_to_currency @project.billable_materials.sum(:price) %></td>
                </tr>
                <tr>
                  <td>Equipment Expenses</td>
                  <td><%=number_to_currency @project.equipment_expenses.sum(:amount) %></td>
                </tr>
                <tr>
                  <td>Purchased Materials</td>
                  <td><%=number_to_currency @project.material_expenses.sum(:price) %></td>
                </tr>
                <tr>
                  <td><strong>Total</strong></td>
                  <td><strong><%=number_to_currency @project.total_expenses %></strong></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div role="tabpanel" class="tab-pane" id="payments">
        <% if @project.bidding.present? %>
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Description</th>
                <% @project.bidders.each do |bidder| %>
                  <th><%= bidder.name %></th>
                <% end %>
              </tr>
            </thead>
            <tbody>
              <% @project.bidding.bid_expenses.each do |bid_expense| %>
                <tr>
                  <td><%= bid_expense %></td>
                  <% @project.bidders.each do |bidder| %>
                    <td>
                      <% @project.bidder_amounts.each do |bidder_amount| %>
                        <% if bidder_amount.bidder_id == bidder.id && bidder_amount.bid_expense_id == bid_expense.id %>
                          <%= bidder_amount.amount %>
                        <% end %>
                      <% end %>
                    </td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="modal-footer">
            <% if @project.bidding.present? %>
              <%=link_to "Set Bidder", new_project_bidder_path(@project), class: "btn btn-primary btn-sm pull-left" %> <%=link_to "Set Bid Amounts", new_project_bidder_amount_path(@project), class: "btn btn-primary btn-sm pull-left" %>
              <%=link_to "Update Bid Expenses", edit_project_bidding_path(@project, @project.bidding.id), class: "btn btn-primary btn-sm pull-right" %>
            <% end %>
          </div>
        <% else %>
          <%=link_to "Set Bid Expenses", new_project_bidding_path(@project), class: "btn btn-primary btn-sm pull-right" %>
        <% end %>
      </div>

      <div role="tabpanel" class="tab-pane" id="permits">
        <h4><center>Materials from Stock</center></h4><hr>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Material</th>
              <th>Quantity</th>
              <th>Contractor</th>
              <th>Cost</th>
              <th>Date Released</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <%@project.billable_materials.each do |billable_material| %>
              <tr>
                <td><%=billable_material.description.titleize %></td>
                <td><%=billable_material.quantity %> <%=billable_material.unit %></td>
                <td><%=billable_material.contractor %></td>
                <td><%=number_to_currency billable_material.total_price %></td>
                <td><%=billable_material.created_at.strftime("%B %d, %Y") %></td>
                <td><%= link_to 'Delete', project_billable_material_path(@project, billable_material.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="modal-footer">
          <%=link_to "Add Material", new_project_billable_material_path(@project), class: "btn btn-primary btn-sm" %>
        </div>
      </div>

      <div class="tab-pane" id="material_expenses">
        <h4><center>Purchased Materials</center></h4><hr>
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Material</th>
              <th>Quantity</th>
              <th>Cost</th>
              <th>Date Released</th>
              <th>Contractor</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <%@project.material_expenses.each do |material_expense| %>
              <tr>
                <td><%=material_expense.description.titleize %></td>
                <td><%=material_expense.quantity %> <%=material_expense.unit %></td>
                <td><%=number_to_currency material_expense.price %></td>
                <td><%=material_expense.created_at.strftime("%B %d, %Y") %></td>
                <td><%=material_expense.contractor %></td>
                <td><%= link_to "Edit", edit_project_material_expense_path(@project, material_expense.id) %> | <%= link_to 'Delete', project_material_expense_path(@project, material_expense.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="modal-footer">
          <%=link_to "Add Material", new_project_material_expense_path(@project), class: "btn btn-primary btn-sm" %>
        </div>
      </div>

      <div role="tabpanel" class="tab-pane" id="equipments">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Equipment</th>
              <th>Dates</th>
              <th>Number of Days</th>
              <th>Actions</th>
             </tr>
          </thead>
          <tbody>
            <%@project.equipment_schedules.each do |equipment_schedule| %>
              <tr>
                <td><%=link_to equipment_schedule.equipment, equipment_path(equipment_schedule.equipment)%></td>
                <td><%=equipment_schedule.starting_date.strftime("%B %d, %Y") %> - <%=equipment_schedule.end_date.strftime("%B %d, %Y")  %></td>
                <td><%=equipment_schedule.number_of_days %> Days</td>
                <td><%= link_to "Edit", edit_project_equipment_schedule_path(@project, equipment_schedule.id) %> | <%= link_to 'Delete', project_equipment_schedule_path(@project, equipment_schedule.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="modal-footer">
          <%=link_to "Add Equipment", new_project_equipment_schedule_path(@project), class: "btn btn-primary btn-sm" %>
        </div>
      </div>

      <div role="tabpanel" class="tab-pane" id="reports">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>Name</th>
              <th>Date Uploaded</th>
              <th class="text-muted">Actions</th>
             </tr>
          </thead>
          <tbody>
            <% @project.uploads.order("created_at desc").each do |upload| %>
              <tr>
              <td><%= link_to upload.uploaded_file_file_name, project_upload_path(@project, upload.id) %></td>
              <td><%= upload.created_at.strftime("%B %e, %Y") %></td>
              <td><%= link_to 'Destroy', project_upload_path(@project, upload.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="modal-footer">
          <%=link_to "Add Reports", new_project_upload_path(@project), class: "btn btn-primary btn-sm" %>
        </div>
      </div>
    </div>
  </div>
</div>