config/routes.rb
Rails.application.routes.draw do

  resources :locations
  root "projects#index"
  resources :materials
  resources :contractors
  resources :uploads
  devise_for :users
  resources :operators
  resources :bid_expenses
  
  resources :petty_cashes do
    resources :particulars
    resources :cash_sources
  end

  resources :equipments do 
    resources :equipment_expenses
  end
  
  resources :projects do 
    resources :billable_materials
    resources :equipment_schedules
    resources :uploads
    resources :material_expenses
    resources :locations
    resources :biddings
    resources :bidders
    resources :bidder_amounts
    resources :bid_collections
  end
    resources :billable_materials
    resources :equipment_schedules
    resources :material_expenses

end

app/models/particular.rb
class Particular < ActiveRecord::Base
  belongs_to :petty_cash
end

app/controllers/particulars_controller.rb
class ParticularsController < ApplicationController
  before_action :set_particular, only: [:show, :edit, :update, :destroy]

  # GET /particulars
  # GET /particulars.json
  def index
    @particulars = Particular.all
  end

  # GET /particulars/1
  # GET /particulars/1.json
  def show
  end

  # GET /particulars/new
  def new
    @petty_cash = PettyCash.find(params[:petty_cash_id])
    @particular = @petty_cash.particulars.build
  end

  # GET /particulars/1/edit
  def edit
  end

  # POST /particulars
  # POST /particulars.json
  def create
    @petty_cash = PettyCash.find(params[:petty_cash_id])
    @particular = @petty_cash.particulars.create(particular_params)

    respond_to do |format|
      if @particular.save
        format.html { redirect_to @petty_cash, notice: 'Particular was successfully created.' }
        format.json { render :show, status: :created, location: @particular }
      else
        format.html { render :new }
        format.json { render json: @particular.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /particulars/1
  # PATCH/PUT /particulars/1.json
  def update
    respond_to do |format|
      if @particular.update(particular_params)
        format.html { redirect_to @particular, notice: 'Particular was successfully updated.' }
        format.json { render :show, status: :ok, location: @particular }
      else
        format.html { render :edit }
        format.json { render json: @particular.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /particulars/1
  # DELETE /particulars/1.json
  def destroy
    @petty_cash = PettyCash.find(params[:petty_cash_id])
    @particular.destroy
    respond_to do |format|
      format.html { redirect_to @petty_cash, notice: 'Particular was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_particular
      @particular = Particular.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def particular_params
      params.require(:particular).permit(:description, :recipient, :amount)
    end
end

app/helpers/particulars_helper.rb
module ParticularsHelper
end

app/views/particulars/_form.html.erb
<%= simple_form_for [@petty_cash, @particular] do |f| %>
  <%= f.error_notification %>
	<div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <% if @particular.new_record? %>
          <h4>New Expenditure</h4>
        <% else %>
          <h4>Update Expenditure</h4>
        <% end %>
      </div>
      <div class="panel-body">
		    <%= f.input :description, input_html: {class: "input-sm"} %>
        <%= f.input :recipient, input_html: {class: "input-sm"} %>
		    <%= f.input :amount, input_html: {class: "input-sm", max: @petty_cash.set_total} %>
		  </div>
			<div class="modal-footer">
        <div class="pull-left">
          <%= link_to "Cancel", petty_cash_path(@petty_cash), class: "btn btn-warning btn-sm" %>
        </div>
        <div class="pull-right">
          <% if @particular.new_record? %>
            <%= f.submit "Save", class: "btn btn-primary btn-sm" %>
          <% else %>
            <%= f.submit "Update", class: "btn btn-primary btn-sm" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/particulars/edit.html.erb
<%= render 'form' %>

app/views/particulars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Particulars</h1>

<table>
  <thead>
    <tr>
      <th>Petty cash</th>
      <th>Description</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @particulars.each do |particular| %>
      <tr>
        <td><%= particular.petty_cash %></td>
        <td><%= particular.description %></td>
        <td><%= particular.amount %></td>
        <td><%= link_to 'Show', particular %></td>
        <td><%= link_to 'Edit', edit_particular_path(particular) %></td>
        <td><%= link_to 'Destroy', particular, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Particular', new_particular_path %>

app/views/particulars/new.html.erb
<%= render 'form' %>

app/views/particulars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Petty cash:</strong>
  <%= @particular.petty_cash %>
</p>

<p>
  <strong>Description:</strong>
  <%= @particular.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @particular.amount %>
</p>

<%= link_to 'Edit', edit_particular_path(@particular) %> |
<%= link_to 'Back', particulars_path %>